### ISSUE TITLE
Facial animation demo missing

### ISSUE THREAD

**Issue by BTakacs-Oxit** [Danial-Kord/DigiHuman#10]
Hello Danial,

This is a great work. I tried running it, but it seems some prefabs are missing and I also could not find the sample for facial animation.
Could you please let me know how to get those?
Thank you in advance

**Comment by Danial-Kord** [comment]
Hey there,

I appreciate your interest in my project. Thank you for letting me know about the missing sample of facial animation. I will try to add it to the project soon(I will let you know in this thread when I add it).

Cheers,

**Comment by Danial-Kord** [comment]
Hello, again dear,

I have added 2 demo animations(pose and facial animations).
You can test the application by selecting provided animations from the right-side UI menu.

P.S. note that the facial animation is much more powerful than provided character(Unity-chan). It is because it does not have many blend mesh values that we can alter to create different animations. To have your ultimate power of facial animations, you need to add new characters with a variety of blendshapes(like the one in my gifs).
I can not add them because they are not free to use.

I will now close this thread as it is fixed.
Feel free to open it if you have more issues.

Cheers,
Danial
